#!/bin/bash
OPCIONES="-decode:width 1 -issue:width 1 -issue:inorder true -commit:width 1 -cache:il1 il1:256:32:1:l -cache:dl1 dl1:256:32:1:l -cache:il2 none -cache:dl2 none"
echo "Caché de correspondencia directa"
echo
for p in filas filas_opt columnas columnas_opt prod_elem prod_elem_opt
do
  echo "Programa $p"
  ./sim-outorder $OPCIONES "$p" 2>&1 | awk '/sim_num_insn/ {print}; /sim_cycle/ {print}' 
done
